sudo: required
services:
  - docker

before_install:
  - docker build -t eddie0228/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eddie0228/docker-react npm run test -- --coverage
