sudo: required
services:
  - docker

before_install:
  - docker build -t eddie0228/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eddie0228/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-east-1-534398133629"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
